### ISSUE TITLE
同步钉钉人员到本地错误

### ISSUE THREAD

**Issue by 764763903a** [jeecgboot/jeecg-boot#2990]
##### 版本号：
2.4.6

##### 问题描述：

同步钉钉人员到本地错误  无同步部门按钮
[DEPART_LIST_SUB_BY_PARENT_ID]   获取成功后报错

        // 查询钉钉所有的部门，用于同步用户和部门的关系
        List<Department> allDepartment = JdtDepartmentAPI.listAll(accessToken);
此代码报错
##### 截图&代码：
![image](https://user-images.githubusercontent.com/28725946/132170514-ca2ff28b-4f5b-4cb5-8407-617ca653cf77.png)
![image](https://user-images.githubusercontent.com/28725946/132170558-01edb1e8-5461-4096-bd3c-cdc8e8e497a2.png)

2021-09-06 14:23:23.444 [http-nio-8080-exec-6] ERROR o.jeecg.common.exception.JeecgBootExceptionHandler:57 - com.alibaba.fastjson.JSONObject incompatible with com.jeecg.dingtalk.api.department.vo.Department
java.lang.ClassCastException: com.alibaba.fastjson.JSONObject incompatible with com.jeecg.dingtalk.api.department.vo.Department
	at com.jeecg.dingtalk.api.department.JdtDepartmentAPI.listAllGetChildren(JdtDepartmentAPI.java:243)
	at com.jeecg.dingtalk.api.department.JdtDepartmentAPI.listAll(JdtDepartmentAPI.java:232)
	at org.jeecg.modules.system.service.impl.ThirdAppDingtalkServiceImpl.syncThirdAppUserToLocal(ThirdAppDingtalkServiceImpl.java:349)
	at org.jeecg.modules.system.controller.ThirdAppController.syncDingtalkUserToLocal(ThirdAppController.java:181)
	at org.jeecg.modules.system.controller.ThirdAppController$$FastClassBySpringCGLIB$$124dc17a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at org.jeecg.common.aspect.DictAspect.doAround(DictAspect.java:54)
	at sun.reflect.GeneratedMethodAccessor281.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at org.jeecg.modules.system.controller.ThirdAppController$$EnhancerBySpringCGLIB$$28ecb06a.syncDingtalkUserToLocal(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:450)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:823)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by biuyoudead** [comment]
场景：对接钉钉，同步部门信息到本地
操作：Vue打开钉钉同步组件的参数，服务端开启钉钉同步。

服务端类：ThirdAppController   接口：syncDingtalkDepartToApp

继续排查
如下

根源位置
包：com.jeecg.dingtalk.api.department
类：JdtDepartmentAPI
方法：listAllGetChildren
行 ：243

截图
![未能直接转换成Department](https://user-images.githubusercontent.com/90177003/132174395-0dfb2201-7996-46ff-9936-f68cce0ab404.png)

说明：
JsonObject 未能转换成对象  Department

**Comment by 764763903a** [comment]
> 场景：对接钉钉，同步部门信息到本地
> 操作：Vue打开钉钉同步组件的参数，服务端开启钉钉同步。
> 
> 服务端类：ThirdAppController 接口：syncDingtalkDepartToApp
> 
> 继续排查
> 如下
> 
> 根源位置
> 包：com.jeecg.dingtalk.api.department
> 类：JdtDepartmentAPI
> 方法：listAllGetChildren
> 行 ：243
> 
> 截图
> ![未能直接转换成Department](https://user-images.githubusercontent.com/90177003/132174395-0dfb2201-7996-46ff-9936-f68cce0ab404.png)
> 
> 说明：
> JsonObject 未能转换成对象 Department

那关于同步钉钉按钮没有出现的情况是什么问题

**Comment by 764763903a** [comment]
private static void listAllGetChildren(int parentDepId, String accessToken, List<Department> all) {
        Response<List<Department>> response = listByParentId(parentDepId, accessToken);
        if (response.isSuccess()) {
            List<Department> departments = (List)response.getResult();
            if (departments.size() != 0) {
                all.addAll(departments);
                Iterator var5 = departments.iterator();

                while(var5.hasNext()) {
                    Department department = (Department)var5.next();
                    listAllGetChildren(department.getDept_id(), accessToken, all);
                }
            }
        }

    }
}

根源位置
包：com.jeecg.dingtalk.api.department
类：JdtDepartmentAPI
方法：listAllGetChildren
行 ：162

截图
![image](https://user-images.githubusercontent.com/28725946/132178889-f971e6e7-65db-4e99-b21a-883adef2091a.png)

多了一个字段 .next强转失败

![image](https://user-images.githubusercontent.com/28725946/132178830-dd217850-3a12-4895-bd34-19d42a4eb39a.png)

**Comment by biuyoudead** [comment]
有没有vue前台开启啊

**Comment by 764763903a** [comment]
> 有没有vue前台开启啊

有 开启了。。。。

**Comment by 764763903a** [comment]
> 解决同步提示失败：两步
> 1、修改 jeecg 的jar包的class文件。路径本地maven仓库下：\org\jeecgframework\jeewx-api\1.4.5\jeewx-api-1.4.5.jar
> 打开jar包 找到 \com\jeecg\dingtalk\api\department，将下图位置复制替换掉
> ![Snipaste_2021-09-07_18-29-36](https://user-images.githubusercontent.com/90177003/132330135-26a683cd-4b10-403f-ad16-beacca313373.png)
> `private static void listAllGetChildren(int parentDepId, String accessToken, List all) {
> Response<List> response = listByParentId(parentDepId, accessToken);
> if (response.isSuccess()) {
> List departments = (List)response.getResult();
> if (departments.size() != 0) {
> all.addAll(departments);
> Iterator var5 = departments.iterator();
> 
> ```
>             while(var5.hasNext()) {
>                 Department department = (Department)JSON.toJavaObject((JSON)JSON.toJSON(var5.next()), Department.class);
>                 listAllGetChildren(department.getDept_id(), accessToken, all);
>             }
>         }
>     }
> 
> }`
> ```
> 
> 2、修改项目工程路径 src/main/java/org/jeecg/modules/system/vo/thirdapp/JdtDepartmentTreeVo.java 文件
> ![Snipaste_2021-09-07_18-30-39](https://user-images.githubusercontent.com/90177003/132330306-d0ed67fd-f4d7-4385-8cd8-32df6dba1189.png)
> 
> `private static List<JdtDepartmentTreeVo> getByParentId(Integer parentId, List<Department> allDepartment) { List<JdtDepartmentTreeVo> list = new ArrayList<>(); if(allDepartment.size()!=0){ Iterator var5=allDepartment.listIterator(); while(var5.hasNext()){ Department department= JSON.toJavaObject((JSON) JSON.toJSON(var5.next()),Department.class); if (parentId.equals(department.getParent_id())) { list.add(new JdtDepartmentTreeVo(department)); } } } return list; } `
> 
> 上述两部分完成就能成功提示同步成功。！但是界面刷新仍不显示

咨询一下 现在问题解决了吗铁子

**Comment by sjlei** [comment]
这个问题是`fastjson`的bug，升级到最新版`1.2.78`就好了

`jeecg-boot-framework\pom.xml`
![image](https://user-images.githubusercontent.com/34293221/133085819-84303d18-a6c5-416a-80aa-6c57f2b93738.png)

**Comment by zhangdaiscott** [comment]
已经上传最新代码，请验证

**Comment by zhangdaiscott** [comment]
我们的逻辑只做平台同步到钉钉，未做钉钉同步到平台，需要的可以自己二开

**Comment by yeafel666** [comment]
> 我们的逻辑只做平台同步到钉钉，未做钉钉同步到平台，需要的可以自己二开

目前部门管理加入syncToLocal无法显示  钉钉同步按钮 ，是Bug么。

**Comment by tanhaican** [comment]
当前版本依然无法看到哎

**Comment by tanhaican** [comment]
> 当前版本依然无法看到哎

在菜单管理中将部门管理对应的前端组件由 [DepartList] -> [DepartListSync]即可

**Comment by biuyoudeaad** [comment]
> 场景：对接钉钉，同步部门信息到本地
> 操作：Vue打开钉钉同步组件的参数，服务端开启钉钉同步。
> 
> 服务端类：ThirdAppController   接口：syncDingtalkDepartToApp
> 
> 继续排查
> 如下
> 
> 根源位置
> 包：com.jeecg.dingtalk.api.department
> 类：JdtDepartmentAPI
> 方法：listAllGetChildren
> 行 ：243
> 
> 截图
> ![未能直接转换成Department](https://user-images.githubusercontent.com/90177003/132174395-0dfb2201-7996-46ff-9936-f68cce0ab404.png)
> 
> 说明：
> JsonObject 未能转换成对象  Department
> 
> 
> 

嘎嘎
