### ISSUE TITLE
Vue解决报错8_打包时TyeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by ma19881117** [jeecgboot/jeecg-boot#3149]
##### 问题描述：
Vue解决报错8_打包时TyeError: Class extends value undefined is not a constructor or null
执行num run build:prod 报错，但是npm run dev没问题

##### 截图&代码：

-  Building for production... ERROR  TypeError: Class extends value undefined is not a constructor or null
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (D:\workspace\git\mrj\jeecg-boot\ant-design-vue-jeecg\node_modules\mini-css-extract-plugin\dist\CssDependency.js:12:46)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (D:\workspace\git\mrj\jeecg-boot\ant-design-vue-jeecg\node_modules\mini-css-extract-plugin\dist\index.js:12:45)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (D:\workspace\git\mrj\jeecg-boot\ant-design-vue-jeecg\node_modules\mini-css-extract-plugin\dist\cjs.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  

解决办法：

执行npm add webpack@4.5.0，解决
原文链接：https://blog.csdn.net/qq_24654501/article/details/115254960

**Comment by zhangdaiscott** [comment]
删除依赖，重新install
