### ISSUE TITLE
微服务部署时出现时间格式转换失败,token失效

### ISSUE THREAD

**Issue by 313988838** [jeecgboot/jeecg-boot#3273]
##### 问题描述：
微服务部署到liunx环境下,新增的模块跟system模块分开部署后再前端界面点击新增模块的列表时出现登录失效,
后台显示时间转换错误,系统自动登出。

##### 截图&代码：
日志错误截图：
![1639472479(1)](https://user-images.githubusercontent.com/50324299/145966617-82824901-e74d-48a4-9097-74873e01616d.jpg)
前端界面报错截图：
![image](https://user-images.githubusercontent.com/50324299/145966900-27c5ad42-db5e-42fd-aaf2-87becfa101cc.png)
网上说org.springframework.validation.BeanPropertyBindingResult: 3 errors这个错误是因为json格式问题。但修改也无效。
如下nacos的时间格式截图：
![image](https://user-images.githubusercontent.com/50324299/145967172-5808b251-0246-4b16-878d-be8a54dd5d57.png)
部署方式：
![1639472915(1)](https://user-images.githubusercontent.com/50324299/145967999-69b6640e-6b9c-4e12-b5bc-f40f457b840a.jpg)

![image](https://user-images.githubusercontent.com/50324299/145968262-dc1c91e5-14cf-4075-8cfa-0daab127a9f0.png)
错误如下：
2021-12-14 16:39:37.741 [http-nio-7001-exec-4] ERROR o.jeecg.common.exception.JeecgBootExceptionHandler:57 - org.springframework.validation.BeanPropertyBindingResult: 3 errors
Field error in object 'multipleLog' on field 'createTime': rejected value [undefined]; codes [typeMismatch.multipleLog.createTime,typeMismatch.createTime,typeMismatch.java.util.Date,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [multipleLog.createTime,createTime]; arguments []; default message [createTime]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.util.Date' for property 'createTime'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@com.fasterxml.jackson.annotation.JsonFormat @org.springframework.format.annotation.DateTimeFormat @io.swagger.annotations.ApiModelProperty java.util.Date] for value 'undefined'; nested exception is java.lang.IllegalArgumentException: Invalid format: "undefined"]
Field error in object 'multipleLog' on field 'flagId': rejected value [undefined]; codes [typeMismatch.multipleLog.flagId,typeMismatch.flagId,typeMismatch.java.lang.Integer,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [multipleLog.flagId,flagId]; arguments []; default message [flagId]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Integer' for property 'flagId'; nested exception is java.lang.NumberFormatException: For input string: "undefined"]
Field error in object 'multipleLog' on field 'openTime': rejected value [undefined]; codes [typeMismatch.multipleLog.openTime,typeMismatch.openTime,typeMismatch.java.util.Date,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [multipleLog.openTime,openTime]; arguments []; default message [openTime]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.util.Date' for property 'openTime'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@com.fasterxml.jackson.annotation.JsonFormat @org.jeecgframework.poi.excel.annotation.Excel @org.springframework.format.annotation.DateTimeFormat @io.swagger.annotations.ApiModelProperty java.util.Date] for value 'undefined'; nested exception is java.lang.IllegalArgumentException: Invalid format: "undefined"]
org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 3 errors
Field error in object 'multipleLog' on field 'createTime': rejected value [undefined]; codes [typeMismatch.multipleLog.createTime,typeMismatch.createTime,typeMismatch.java.util.Date,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [multipleLog.createTime,createTime]; arguments []; default message [createTime]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.util.Date' for property 'createTime'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@com.fasterxml.jackson.annotation.JsonFormat @org.springframework.format.annotation.DateTimeFormat @io.swagger.annotations.ApiModelProperty java.util.Date] for value 'undefined'; nested exception is java.lang.IllegalArgumentException: Invalid format: "undefined"]
Field error in object 'multipleLog' on field 'flagId': rejected value [undefined]; codes [typeMismatch.multipleLog.flagId,typeMismatch.flagId,typeMismatch.java.lang.Integer,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [multipleLog.flagId,flagId]; arguments []; default message [flagId]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Integer' for property 'flagId'; nested exception is java.lang.NumberFormatException: For input string: "undefined"]
Field error in object 'multipleLog' on field 'openTime': rejected value [undefined]; codes [typeMismatch.multipleLog.openTime,typeMismatch.openTime,typeMismatch.java.util.Date,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [multipleLog.openTime,openTime]; arguments []; default message [openTime]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.util.Date' for property 'openTime'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@com.fasterxml.jackson.annotation.JsonFormat @org.jeecgframework.poi.excel.annotation.Excel @org.springframework.format.annotation.DateTimeFormat @io.swagger.annotations.ApiModelProperty java.util.Date] for value 'undefined'; nested exception is java.lang.IllegalArgumentException: Invalid format: "undefined"]
        at org.springframework.web.method.annotation.ModelAttributeMethodProcessor.resolveArgument(ModelAttributeMethodProcessor.java:164)
        at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121)
        at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:167)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.github.xiaoymin.knife4j.spring.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.github.xiaoymin.knife4j.spring.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:90)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.jeecg.config.shiro.filters.JwtFilter.executeChain(JwtFilter.java:253)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:450)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
应该是部署问题

**Comment by 313988838** [comment]
不是部署问题，群里也有其他的开发者也出现了这个问题。

**Comment by 313988838** [comment]
> 应该是部署问题

不是部署问题呀，群里也有其他开发者他们也出现了这个问题

**Comment by zhangdaiscott** [comment]
本地运行没问题？

**Comment by 313988838** [comment]
> 本地运行没问题？

对的。本地运行没有任何问题。只是再部署后出现这个问题

**Comment by zhangdaiscott** [comment]
试下我们默认的demo模块有无问题，你自己加的，我们无法判断

**Comment by 313988838** [comment]
> 试下我们默认的demo模块有无问题，你自己加的，我们无法判断

好的。我先试试。

**Comment by 313988838** [comment]
> 试下我们默认的demo模块有无问题，你自己加的，我们无法判断

我们加的项目跟你们原来的模块方式有点区别。
如下我们自己的：
![image](https://user-images.githubusercontent.com/50324299/146292789-c2da5837-bc23-496a-9fd3-2c8b056f290a.png)
如下你们demo的模块方式：
![image](https://user-images.githubusercontent.com/50324299/146292851-380a9b51-17e5-42f3-acbe-fdd7759d2daa.png)
