### ISSUE TITLE
Online Java增强 http-api问题

### ISSUE THREAD

**Issue by IsMrChen** [jeecgboot/jeecg-boot#3441]
##### 版本号：
3.0

##### 问题描述：
Online Java增强 http-api

新增修改了数据想将修改的数据原样返回报错：

2022-02-21 21:20:43.893 [http-nio-8080-exec-5] INFO  org.jeecg.common.util.RestUtil:195 -  RestUtil  --- request ---  url = http://localhost:8080/jeecg-boot/stayApply/hbizStayApply/StayApply
2022-02-21 21:20:43.899 [http-nio-8080-exec-7] INFO  o.j.m.stayApply.controller.HbizStayApplyController:33 - username:chenqiang99
2022-02-21 21:20:43.915 [http-nio-8080-exec-5] ERROR org.jeecg.modules.online.cgform.c.a:350 - OnlCgformApiController.formAdd()发生异常：
java.lang.NullPointerException: null
	at org.jeecg.modules.online.cgform.enhance.impl.http.a.execute(CgformEnhanceHttpFormImpl.java:30)
	at org.jeecg.modules.online.cgform.service.a.d.a(OnlCgformHeadServiceImpl.java:1187)
	at org.jeecg.modules.online.cgform.service.a.d.executeEnhanceJava(OnlCgformHeadServiceImpl.java:1197)
	at org.jeecg.modules.online.cgform.service.a.d.saveManyFormData(OnlCgformHeadServiceImpl.java:869)
	at org.jeecg.modules.online.cgform.service.a.d$$FastClassBySpringCGLIB$$76271ae2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)

##### 截图&代码：
	@PostMapping("/StayApply")
	public Result<JSONObject> startStayApply(@RequestBody JSONObject params,HttpServletRequest request){
		JSONObject json = params.getJSONObject("json");
		json.put("flow_id","123");
		params.put("json",json);
		JSONObject res = new JSONObject();
		res.put("code",1);
		res.put("record",json);
		return Result.OK(res);
	}

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
新版文档里获取当前行数据的属性名已经改成`record`了
![image](https://user-images.githubusercontent.com/34293221/156486752-f3c94da7-d463-4edb-87e8-e89ab2400294.png)

你只需要改成`params.getJSONObject("record")` 即可
![image](https://user-images.githubusercontent.com/34293221/156486832-265db2e1-c244-4edd-aef4-b4c232bb3387.png)
