### ISSUE TITLE
Cannot read properties of undefined (reading 'methods')

### ISSUE THREAD

**Issue by k1195453766** [jeecgboot/jeecg-boot#3652]
##### 版本号：
2.6,10

##### 问题描述：
启动项目一直卡在加载页面，进不去登陆页面，提示下边错误

##### 截图&代码：
Uncaught TypeError: Cannot read properties of undefined (reading 'methods')
    at eval (install.js?61dd:20:1)
    at Module../src/components/jeecg/JVxeTable/install.js (app.js:24876:1)
    at __webpack_require__ (app.js:833:30)
    at fn (app.js:130:20)
    at eval (index.js:5:66)
    at Module../src/components/jeecg/JVxeTable/index.js (app.js:24864:1)
    at __webpack_require__ (app.js:833:30)
    at fn (app.js:130:20)
    at eval (cjs.js?!./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/jeecg/JVxeDemo/layout-demo/Template1.vue?vue&type=script&lang=js&:3:85)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/jeecg/JVxeDemo/layout-demo/Template1.vue?vue&type=script&lang=js& (app.js:8809:1)

**Comment by zhangdaiscott** [comment]
删除依赖，重新install

**Comment by k1195453766** [comment]
> 删除依赖，重新install

重新install，不管用，还是一样的报错呢 @zhangdaiscott
