### ISSUE TITLE
online 表单中，某一字段含有[123,456,789]这种格式时，前台编辑报错

### ISSUE THREAD

**Issue by 793292556** [jeecgboot/jeecg-boot#3675]
##### 版本号：
3.1

##### 问题描述：
online 表单中，某一字段含有[123,456,789]这种格式时，前台点击“编辑”按钮时报错，
该字段实际存储数值不应用于解析，但是前台显示时给解析了

##### 截图&代码：

org.jeecg.modules.online.cgform.c.a:273 - Online表单查询异常：syntax error, pos 3, line 1, column 4[123, 14566, 157, 15700178, 100179]
com.alibaba.fastjson.JSONException: syntax error, pos 3, line 1, column 4[123, 14566, 157, 15700178, 100179]
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1510)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1390)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1268)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1169)
	at com.alibaba.fastjson.JSON.parseArray(JSON.java:612)
	at com.alibaba.fastjson.JSON.parseArray(JSON.java

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
ty

**Comment by tygithub1** [comment]
什么字段，怎么配置的，输入框测试无此问题

**Comment by 793292556** [comment]
将一个arraylist.tostring 直接存入数据库对应字符串中，然后前台编辑这个字符串对应的数据就有问题

从 Windows 版邮件发送

发件人: tygithub1
发送时间: 2022年5月25日 19:36
收件人: jeecgboot/jeecg-boot
抄送: 793292556; Author
主题: Re: [jeecgboot/jeecg-boot] online 表单中，某一字段含有[123,456,789]这种格式时，前台编辑报错 (Issue #3675)

什么字段，怎么配置的，输入框测试无此问题
