### ISSUE TITLE
Name for argument of type [java.lang.String] not specified如何解决

### ISSUE THREAD

**Issue by LancCJ** [jeecgboot/jeecg-boot#3825]
##### 版本号：
2.4.6

##### 问题描述：

查看 另一个 issue 但是并未给出解决办法就说解决了。。。都没有说怎么解决的就close了

在积木在线报表设计过程中，按照WIKI：
[http://doc.jeecg.com/2373083](https://gitee.com/link?target=http%3A%2F%2Fdoc.jeecg.com%2F2373083) 进行配置，在解析过程 控制台报错

online 表名是:jx_customer_price_main

##### 截图&代码：

2022-06-23 09:05:56.258 [http-nio-8080-exec-5] INFO org.jeecg.modules.jmreport.desreport.a.a:720 - 报表executeSelectApi:: api= {{ domainURL }}/online/cgform/api/data/jx_customer_price_main/queryById?id=1537230863492788226&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NTU5NDU5NDcsInVzZXJuYW1lIjoiYWRtaW4ifQ.UCFLXM4rVVaRcHAnBoG9syNk34QbYXr776PvwCvgzeA, method= 0, token= eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NTU5NDU5NDcsInVzZXJuYW1lIjoiYWRtaW4ifQ.UCFLXM4rVVaRcHAnBoG9syNk34QbYXr776PvwCvgzeA
2022-06-23 09:05:56.260 [http-nio-8080-exec-5] INFO org.jeecg.modules.jmreport.desreport.service.a.i:594 - 报表API 查询sendHttpRequest 原始API=> {{ domainURL }}/online/cgform/api/data/jx_customer_price_main/queryById?id=1537230863492788226&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NTU5NDU5NDcsInVzZXJuYW1lIjoiYWRtaW4ifQ.UCFLXM4rVVaRcHAnBoG9syNk34QbYXr776PvwCvgzeA
2022-06-23 09:05:56.318 [http-nio-8080-exec-5] INFO org.jeecg.modules.jmreport.desreport.service.a.i:597 - 报表API 查询sendHttpRequest 替换后API=> [http://localhost:8080/jeecg-boot/online/cgform/api/data/jx_customer_price_main/queryById?id=1537230863492788226&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NTU5NDU5NDcsInVzZXJuYW1lIjoiYWRtaW4ifQ.UCFLXM4rVVaRcHAnBoG9syNk34QbYXr776PvwCvgzeA](https://gitee.com/link?target=http%3A%2F%2Flocalhost%3A8080%2Fjeecg-boot%2Fonline%2Fcgform%2Fapi%2Fdata%2Fjx_customer_price_main%2FqueryById%3Fid%3D1537230863492788226%26token%3DeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NTU5NDU5NDcsInVzZXJuYW1lIjoiYWRtaW4ifQ.UCFLXM4rVVaRcHAnBoG9syNk34QbYXr776PvwCvgzeA)
2022-06-23 09:05:56.319 [http-nio-8080-exec-5] INFO org.jeecg.modules.jmreport.desreport.service.a.i:598 - 报表API 查询sendHttpRequest Method=> 0
2022-06-23 09:05:56.328 [http-nio-8080-exec-6] ERROR o.jeecg.common.exception.JeecgBootExceptionHandler:57 - Name for argument of type [java.lang.String] not specified, and parameter name information not found in class file either.
java.lang.IllegalArgumentException: Name for argument of type [java.lang.String] not specified, and parameter name information not found in class file either.
at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.updateNamedValueInfo(AbstractNamedValueMethodArgumentResolver.java:172)
at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.getNamedValueInfo(AbstractNamedValueMethodArgumentResolver.java:149)
at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:99)
at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121)
at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:167)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:450)
at org.apache.shiro.web.servlet.AbstractShiroFilter1.call(AbstractShiroFilter.java:365) 
at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) 
at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) 
at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387) 
at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) 
at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92) 
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88) 
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) 
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) 
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) 
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) 
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) 
at org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:97) 
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:41002) 
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) 
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) 
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) 
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) 
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) 
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) 
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) 
at org.apache.coyote.AbstractProtocolConnectionHandler.process(AbstractProtocol.java:868)
at org.apache.tomcat.util.net.NioEndpointSocketProcessor.doRun(NioEndpoint.java:1590)atorg.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)atjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)atjava.util.concurrent.ThreadPoolExecutorWorker.run(ThreadPoolExecutor.java:624)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:750)
2022-06-23 09:05:56.334 [http-nio-8080-exec-5] INFO org.jeecg.modules.jmreport.desreport.service.a.i:613 - 报表API 查询sendHttpRequest result=> {"success":false,"message":"操作失败，Name for argument of type [java.lang.String] not specified, and parameter name information not found in class file either.","code":500,"result":null,"timestamp":1655946356332}
2022-06-23 09:16:08.513 [http-nio-8080-exec-1] INFO org.jeecg.common.system.query.QueryGenerator:535 - --查询规则-->copy_type = 0
2022-06-23 09:16:08.530 [http-nio-8080-exec-1] INFO org.jeecg.common.system.query.QueryGenerator:227 - 排序规则>>列:createTime,排序方式:desc

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
把代码升级到最新版
