### ISSUE TITLE
前端打包部署报错- "version": "3.1.0",

### ISSUE THREAD

**Issue by dhanyue** [jeecgboot/jeecg-boot#3920]
##### 截图&代码：
Uncaught ReferenceError: Vue is not defined
    at 8bbf (app.24893fbf.js:1:397536)
    at c (app.24893fbf.js:1:12430)
    at 56d7 (app.24893fbf.js:1:229901)
    at c (app.24893fbf.js:1:12430)
    at 0 (app.24893fbf.js:1:31110)
    at c (app.24893fbf.js:1:12430)
    at n (app.24893fbf.js:1:431)
    at app.24893fbf.js:1:31075
    at app.24893fbf.js:1:31080
![image](https://user-images.githubusercontent.com/6113896/180921412-50226906-b6ee-4072-a287-bc87e49301f4.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by dhanyue** [comment]
已解决，webpack配置，cdn地址不能访问导致；
![image](https://user-images.githubusercontent.com/6113896/180961473-927d8da0-52c3-45cf-893e-1fd2bcee042a.png)

**Comment by zhangdaiscott** [comment]
这是你自己加的吧
