### ISSUE TITLE
微服务版system模块启动报错Error creating bean with name 'initCodeGenerateDbConfig' defined in class path resource

### ISSUE THREAD

**Issue by ice2shell** [jeecgboot/jeecg-boot#3970]
##### 版本号：
3.4.0

##### 问题描述：
#3967 拆分出独立的单体启动模块后，自定义了一个微服务版本的system启动模块pom dependencies 如下：
```
<dependencies>
        <!-- 引入jeecg-boot-starter-cloud依赖 -->
        <dependency>
            <groupId>org.jeecgframework.boot</groupId>
            <artifactId>jeecg-boot-starter-cloud</artifactId>
        </dependency>
        <!-- jeecg-system-biz依赖 -->
        <dependency>
            <groupId>org.jeecgframework.boot</groupId>
            <artifactId>jeecg-system-biz</artifactId>
        </dependency>

    </dependencies>
```

然后启动就报错`Error creating bean with name 'initCodeGenerateDbConfig' defined in class path resource`。
看报错日志，发现是 `Can't find bundle for base name jeecg/jeecg_database`。将`jeecg-system-start`模块`src/main/resources/jeecg`路径下的俩文件复制到`jeecg-system-biz`模块同名路径下可以临时解决。报错日志如下：
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'initCodeGenerateDbConfig' defined in class path resource [org/jeecg/config/init/CodeGenerateDbConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jeecg.config.init.CodeGenerateDbConfig]: Factory method 'initCodeGenerateDbConfig' threw exception; nested exception is java.lang.ExceptionInInitializerError
 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.18.jar!/:5.3.18]
 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:486) ~[spring-beans-5.3.18.jar!/:5.3.18]
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.18.jar!/:5.3.18]
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.18.jar!/:5.3.18]
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.18.jar!/:5.3.18]
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.18.jar!/:5.3.18]
 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.18.jar!/:5.3.18]
 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.18.jar!/:5.3.18]
 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.18.jar!/:5.3.18]
 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.18.jar!/:5.3.18]
 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.18.jar!/:5.3.18]
 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.18.jar!/:5.3.18]
 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.18.jar!/:5.3.18]
 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.6.jar!/:2.6.6]
 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[spring-boot-2.6.6.jar!/:2.6.6]
 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[spring-boot-2.6.6.jar!/:2.6.6]
 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-2.6.6.jar!/:2.6.6]
 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[spring-boot-2.6.6.jar!/:2.6.6]
 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.6.jar!/:2.6.6]
 	at org.jeecg.CustomSystemApp.main(CustomSystemApp.java:40) ~[classes!/:3.4.0]
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
 	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app.jar:3.4.0]
 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[app.jar:3.4.0]
 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app.jar:3.4.0]
 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[app.jar:3.4.0]
 Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jeecg.config.init.CodeGenerateDbConfig]: Factory method 'initCodeGenerateDbConfig' threw exception; nested exception is java.lang.ExceptionInInitializerError
 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.18.jar!/:5.3.18]
 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.18.jar!/:5.3.18]
 	... 27 common frames omitted
 Caused by: java.lang.ExceptionInInitializerError: null
 	at org.jeecgframework.codegenerate.database.CodegenDatasourceConfig.initDbConfig(CodegenDatasourceConfig.java:20) ~[codegenerate-1.3.9.jar!/:2.0.0]
 	at org.jeecg.config.init.CodeGenerateDbConfig.initCodeGenerateDbConfig(CodeGenerateDbConfig.java:45) ~[jeecg-system-biz-3.4.0.jar!/:3.4.0]
 	at org.jeecg.config.init.CodeGenerateDbConfig$$EnhancerBySpringCGLIB$$eb08dd9.CGLIB$initCodeGenerateDbConfig$0(<generated>) ~[jeecg-system-biz-3.4.0.jar!/:3.4.0]
 	at org.jeecg.config.init.CodeGenerateDbConfig$$EnhancerBySpringCGLIB$$eb08dd9$$FastClassBySpringCGLIB$$b3e6af39.invoke(<generated>) ~[jeecg-system-biz-3.4.0.jar!/:3.4.0]
 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.18.jar!/:5.3.18]
 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.18.jar!/:5.3.18]
 	at org.jeecg.config.init.CodeGenerateDbConfig$$EnhancerBySpringCGLIB$$eb08dd9.initCodeGenerateDbConfig(<generated>) ~[jeecg-system-biz-3.4.0.jar!/:3.4.0]
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
 	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.18.jar!/:5.3.18]
 	... 28 common frames omitted
 Caused by: java.util.MissingResourceException: Can't find bundle for base name jeecg/jeecg_database, locale en
 	at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055) ~[na:na]
 	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689) ~[na:na]
 	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593) ~[na:na]
 	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1556) ~[na:na]
 	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:857) ~[na:na]
 	at org.jeecgframework.codegenerate.a.a.<clinit>(CodeConfigProperties.java:36) ~[codegenerate-1.3.9.jar!/:2.0.0]
 	... 40 common frames omitted
 
```

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
提了
