### ISSUE TITLE
微服务@Dict注解显示commonApi异常NoSuchBeanDefinitionException

### ISSUE THREAD

**Issue by ChenZJ0104** [jeecgboot/jeecg-boot#4192]
##### 问题描述：

微服务项目在jeecg-demo-cloud-start服务中的实体类属性上添加@Dict(dicCode="xxx"),在查询相关字段时，报异常：
![Snipaste_2022-11-05_23-07-43](https://user-images.githubusercontent.com/102576024/200126511-f0b4ef98-5014-4a0b-b096-fea5ffb74880.png)

##### 截图&代码：
实体类代码：
@Excel(name = "状态", width = 15)
@ApiModelProperty(value = "状态")
@Dict(dicCode = "refunds")
private String state;

异常日志：
2022-11-05 22:54:21.322 ERROR 8524 --- [nio-7002-exec-1] o.j.c.e.JeecgBootExceptionHandler        : No qualifying bean of type 'org.jeecg.common.api.CommonAPI' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.context.annotation.Lazy(value=true), @org.springframework.beans.factory.annotation.Autowired(required=true)}

org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.jeecg.common.api.CommonAPI' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.context.annotation.Lazy(value=true), @org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1799) ~[spring-beans-5.3.18.jar:5.3.18]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1355) ~[spring-beans-5.3.18.jar:5.3.18]
	at org.springframework.context.annotation.ContextAnnotationAutowireCandidateResolver$1.getTarget(ContextAnnotationAutowireCandidateResolver.java:95) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:195) ~[spring-aop-5.3.18.jar:5.3.18]
	at com.sun.proxy.$Proxy117.translateManyDict(Unknown Source) ~[na:na]
	at org.jeecg.common.aspect.DictAspect.translateAllDict(DictAspect.java:312) ~[classes/:na]
	at org.jeecg.common.aspect.DictAspect.parseDictText(DictAspect.java:166) ~[classes/:na]
	at org.jeecg.common.aspect.DictAspect.doAround(DictAspect.java:68) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634) ~[spring-aop-5.3.18.jar:5.3.18]
......

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你得引入下 jeecg-system-cloud-api

**Comment by ChenZJ0104** [comment]
![image](https://user-images.githubusercontent.com/102576024/200301679-61ab5dd7-ddff-4d54-b9f7-48ac13d4ced1.png)
您好，我引入了 jeecg-system-cloud-api，也重新编译了，但还是报这个异常

**Comment by zhangdaiscott** [comment]
不应该，你下载最新的代码测试下，这个问题修改改过

**Comment by ChenZJ0104** [comment]
您好，使用了3.4.3-GA版本，可以正常翻译了；非常感谢！！
