### ISSUE TITLE
前端linux，jenkins打包失败

### ISSUE THREAD

**Issue by BigRoseAndBoss** [jeecgboot/jeecg-boot#4407]
##### 版本号：
3.4.3-GA

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
用jenkins打包前端项目的时候，报这个错误。
这是打包命令
node -v
npm -v
rm -rf node_modules || true
rm -rf dist || true
npm cache --force clean && npm install --force --unsafe-perm=true
npm install webpack --save-dev
rm -rf node_modules/caniuse-lite
rm -rf node_modules/browserslist
npm i --save-dev caniuse-lite browserslist
npm run build
docker build -t nginx:jeecgboot .
docker run --name jeecg-boot-nginx -p 6060:8000 --restart=always -d nginx:jeecgboot

##### 截图&代码：

[error] [31m[vite:vue] v-model cannot be used on a prop, because local prop bindings are not writable.
Use a v-bind binding combined with a v-on listener that emits update:x event instead.

/var/jenkins_home/workspace/污水厂前端项目/src/components/Form/src/jeecg/components/JSwitch.vue
3  |      <a-select
4  |        v-if="query"
5  |        v-model:value="value"
   |             ^^^^^
6  |        :options="selectOptions"
7  |        :disabled="disabled"
[39m
file: [36m/var/jenkins_home/workspace/污水厂前端项目/src/components/Form/src/jeecg/components/JSwitch.vue:undefined:undefined[39m
[error] [31merror during build:
SyntaxError: v-model cannot be used on a prop, because local prop bindings are not writable.
Use a v-bind binding combined with a v-on listener that emits update:x event instead.

/var/jenkins_home/workspace/污水厂前端项目/src/components/Form/src/jeecg/components/JSwitch.vue
3  |      <a-select
4  |        v-if="query"
5  |        v-model:value="value"
   |             ^^^^^
6  |        :options="selectOptions"
7  |        :disabled="disabled"

    at createCompilerError (/var/jenkins_home/workspace/污水厂前端项目/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:18:19)
    at Object.transformModel (/var/jenkins_home/workspace/污水厂前端项目/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:5267:25)
    at transformModel (/var/jenkins_home/workspace/污水厂前端项目/node_modules/@vue/compiler-dom/dist/compiler-dom.cjs.prod.js:2536:37)
    at buildProps (/var/jenkins_home/workspace/污水厂前端项目/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:4655:48)
    at Array.postTransformElement (/var/jenkins_home/workspace/污水厂前端项目/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:4294:38)
    at traverseNode (/var/jenkins_home/workspace/污水厂前端项目/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:2175:19)
    at traverseChildren (/var/jenkins_home/workspace/污水厂前端项目/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:2117:9)
    at traverseNode (/var/jenkins_home/workspace/污水厂前端项目/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:2168:13)
    at traverseNode (/var/jenkins_home/workspace/污水厂前端项目/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:2161:17)
    at traverseChildren (/var/jenkins_home/workspace/污水厂前端项目/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:2117:9)
    at traverseNode (/var/jenkins_home/workspace/污水厂前端项目/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:2168:13)
    at traverseChildren (/var/jenkins_home/workspace/污水厂前端项目/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:2117:9)
    at traverseNode (/var/jenkins_home/workspace/污水厂前端项目/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:2168:13)
    at transform (/var/jenkins_home/workspace/污水厂前端项目/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:2056:5)
    at Object.baseCompile (/var/jenkins_home/workspace/污水厂前端项目/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:5589:5)
    at Object.compile (/var/jenkins_home/workspace/污水厂前端项目/node_modules/@vue/compiler-dom/dist/compiler-dom.cjs.prod.js:3043:25)
    at doCompileTemplate (/var/jenkins_home/workspace/污水厂前端项目/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3223:49)
    at compileTemplate (/var/jenkins_home/workspace/污水厂前端项目/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3196:16)
    at Object.compileScript (/var/jenkins_home/workspace/污水厂前端项目/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:4461:59)
    at resolveScript (/var/jenkins_home/workspace/污水厂前端项目/node_modules/@vitejs/plugin-vue/dist/index.cjs:269:31)
    at genScriptCode (/var/jenkins_home/workspace/污水厂前端项目/node_modules/@vitejs/plugin-vue/dist/index.cjs:2409:18)
    at transformMain (/var/jenkins_home/workspace/污水厂前端项目/node_modules/@vitejs/plugin-vue/dist/index.cjs:2225:54)
    at Object.transform (/var/jenkins_home/workspace/污水厂前端项目/node_modules/@vitejs/plugin-vue/dist/index.cjs:2705:16)
    at [file:///var/jenkins_home/workspace/%E6%B1%A1%E6%B0%B4%E5%8E%82%E5%89%8D%E7%AB%AF%E9%A1%B9%E7%9B%AE/node_modules/rollup/dist/es/shared/rollup.js:22748:40[39m](file:///var/jenkins_home/workspace/%E6%B1%A1%E6%B0%B4%E5%8E%82%E5%89%8D%E7%AB%AF%E9%A1%B9%E7%9B%AE/node_modules/rollup/dist/es/shared/rollup.js:22748:40%1B[39m)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jeecgboot-vue3@3.4.3 build: `NODE_ENV=production NODE_OPTIONS=--max-old-space-size=8192 vite build && esno ./build/script/postBuild.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jeecgboot-vue3@3.4.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-12-12T21_19_53_371Z-debug.log
Build step 'Execute shell' marked build as failure
Finished: FAILURE

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by BigRoseAndBoss** [comment]
> 跟jenkis没关系，先确认下本地是否可以打包

本地可以打包

**Comment by BigRoseAndBoss** [comment]
![image](https://user-images.githubusercontent.com/50453506/207231860-cb1a4a39-0f84-4324-923c-10528aa64463.png)

linux本地npm run serve ，也报这个错

**Comment by zhangdaiscott** [comment]
更到最新代码看看
