### ISSUE TITLE
websocket 访问无响应

### ISSUE THREAD

**Issue by xiusi-ultimate** [jeecgboot/jeecg-boot#4586]
##### 截图&代码：用ws://127.0.0.1:8080/websocket/   访问没有任何反应，也没有任何信息 

但是前缀用**_wss_** 后台有报错信息，说明是链路是通的

wss 访问的报错信息：
2023-02-17 15:37:56.702 [http-nio-8080-exec-1] INFO  org.apache.coyote.http11.Http11Processor:175 - Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x03}a50xfe"0x120xfc0xe20x880xf3W0x8b0xc5/%0xea0xa9G0xc5s0x050xad0x040xdb0x9d0xac0xf7_0xb95Eq ]. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:419)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:271)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)

我自己本地用这个框架websocket 写demo测试没有问题，放在jeecg 里面有不能用了，尝试了各种办法，也排查了shiro 拦截 ，搞不明白为什么ws的访问后台没有任何结果反馈

**Comment by GitACDreamer** [comment]
@xiusi-ultimate 根据我以前的经验，你这里还是使用了http请求，访问了https接口
```nvalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x03}a50xfe"0x120xfc0xe20x880xf3W0x8b0xc5/%0xea0xa9G0xc5s0x050xad0x040xdb0x9d0xac0xf7_0xb95Eq``` 根据你这段报错看出来

**Comment by tony2y** [comment]
有解决方式吗，遇到同样的问题@xiusi-ultimate @GitACDreamer

**Comment by GitACDreamer** [comment]
> @xiusi-ultimate 根据我以前的经验，你这里还是使用了http请求，访问了https接口

@tony2y 你前端服务器端一致不就OK，服务器端http,前端就http,反之一样。
