### ISSUE TITLE
Vue3版本上传文件会两次调用Upload组件且后台报错

### ISSUE THREAD

**Issue by hkq-hub** [jeecgboot/jeecg-boot#4793]
##### 版本号：
jeecg-boot V3.5.0，

##### 前端版本：
jeecgboot-vue3 V3.5.0

##### 问题描述：
Vue3版本上传文件会两次调用Upload组件且后台报错

##### 截图&代码：

![bf3e3ffffc0dd1cdf436113e1cc09e6](https://user-images.githubusercontent.com/83913511/230315920-dd03fc1a-e7b9-40cf-aee9-32a01f34a43b.png)

后台报错内容：
2023-04-06 15:56:08.065 [http-nio-8080-exec-8] WARN  o.s.w.m.support.StandardServletMultipartResolver:139 - Failed to perform cleanup of multipart items
java.io.UncheckedIOException: Cannot delete C:\Users\Administrator\AppData\Local\Temp\tomcat.8080.6613712556324073871\work\Tomcat\localhost\jeecg-boot\upload_9489f343_9e1d_4fd8_b5aa_d1bc0c95a8d6_00000032.tmp
	at org.apache.tomcat.util.http.fileupload.disk.DiskFileItem.delete(DiskFileItem.java:431)
	at org.apache.catalina.core.ApplicationPart.delete(ApplicationPart.java:54)
	at org.springframework.web.multipart.support.StandardServletMultipartResolver.cleanupMultipart(StandardServletMultipartResolver.java:134)
	at org.springframework.web.servlet.DispatcherServlet.cleanupMultipart(DispatcherServlet.java:1250)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1107)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:696)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:458)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:373)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:370)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Cannot delete C:\Users\Administrator\AppData\Local\Temp\tomcat.8080.6613712556324073871\work\Tomcat\localhost\jeecg-boot\upload_9489f343_9e1d_4fd8_b5aa_d1bc0c95a8d6_00000032.tmp
	... 77 common frames omitted
2023-04-06 15:56:08.073 [http-nio-8080-exec-8] ERROR org.apache.coyote.http11.Http11Processor:175 - Error processing request
java.io.UncheckedIOException: Cannot delete C:\Users\Administrator\AppData\Local\Temp\tomcat.8080.6613712556324073871\work\Tomcat\localhost\jeecg-boot\upload_9489f343_9e1d_4fd8_b5aa_d1bc0c95a8d6_00000032.tmp
	at org.apache.tomcat.util.http.fileupload.disk.DiskFileItem.delete(DiskFileItem.java:431)
	at org.apache.catalina.core.ApplicationPart.delete(ApplicationPart.java:54)
	at org.apache.catalina.connector.Request.recycle(Request.java:483)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:441)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Cannot delete C:\Users\Administrator\AppData\Local\Temp\tomcat.8080.6613712556324073871\work\Tomcat\localhost\jeecg-boot\upload_9489f343_9e1d_4fd8_b5aa_d1bc0c95a8d6_00000032.tmp
	... 13 common frames omitted
2023-04-06 15:56:08.076 [http-nio-8080-exec-8] ERROR org.apache.coyote.http11.Http11NioProtocol:175 - Error reading request, ignored
java.io.UncheckedIOException: Cannot delete C:\Users\Administrator\AppData\Local\Temp\tomcat.8080.6613712556324073871\work\Tomcat\localhost\jeecg-boot\upload_9489f343_9e1d_4fd8_b5aa_d1bc0c95a8d6_00000032.tmp
	at org.apache.tomcat.util.http.fileupload.disk.DiskFileItem.delete(DiskFileItem.java:431)
	at org.apache.catalina.core.ApplicationPart.delete(ApplicationPart.java:54)
	at org.apache.catalina.connector.Request.recycle(Request.java:483)
	at org.apache.catalina.connector.CoyoteAdapter.log(CoyoteAdapter.java:515)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:429)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Cannot delete C:\Users\Administrator\AppData\Local\Temp\tomcat.8080.6613712556324073871\work\Tomcat\localhost\jeecg-boot\upload_9489f343_9e1d_4fd8_b5aa_d1bc0c95a8d6_00000032.tmp
	... 13 common frames omitted
2023-04-06 15:56:08.079 [http-nio-8080-exec-8] ERROR org.apache.tomcat.util.net.NioEndpoint:175 - Error running socket processor
java.io.UncheckedIOException: Cannot delete C:\Users\Administrator\AppData\Local\Temp\tomcat.8080.6613712556324073871\work\Tomcat\localhost\jeecg-boot\upload_9489f343_9e1d_4fd8_b5aa_d1bc0c95a8d6_00000032.tmp
	at org.apache.tomcat.util.http.fileupload.disk.DiskFileItem.delete(DiskFileItem.java:431)
	at org.apache.catalina.core.ApplicationPart.delete(ApplicationPart.java:54)
	at org.apache.catalina.connector.Request.recycle(Request.java:483)
	at org.apache.catalina.connector.CoyoteAdapter.log(CoyoteAdapter.java:515)
	at org.apache.catalina.connector.CoyoteAdapter.checkRecycled(CoyoteAdapter.java:539)
	at org.apache.coyote.http11.Http11Processor.recycle(Http11Processor.java:1439)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.release(AbstractProtocol.java:1098)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:1056)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Cannot delete C:\Users\Administrator\AppData\Local\Temp\tomcat.8080.6613712556324073871\work\Tomcat\localhost\jeecg-boot\upload_9489f343_9e1d_4fd8_b5aa_d1bc0c95a8d6_00000032.tmp
	... 14 common frames omitted

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
经测试vue3线上和本地上传正常，且后台未报错；请debug跟一下代码判断决堤报错原因；
![image](https://user-images.githubusercontent.com/65587928/230847291-b6e100ac-8898-40aa-94e6-671c83d0f0be.png)
![image](https://user-images.githubusercontent.com/65587928/230847629-3917a912-c797-4135-8c35-33808bb9bee4.png)
![image](https://user-images.githubusercontent.com/65587928/230847901-ccfa01e3-fade-4970-8379-47378510f6ec.png)

上传调用两次Upload参考看一下是否是Chrome浏览器的问题
https://blog.csdn.net/bestzy6/article/details/122391822
