### ISSUE TITLE
集成postgresql报错

### ISSUE THREAD

**Issue by yjtcxd** [jeecgboot/jeecg-boot#4884]
##### 问题描述：
jeecg-boot单体，数据库postgresql，查询字段报错。例如：select 字段1,字段2, ...  from table

### Cause: org.postgresql.util.PSQLException: ERROR: column "id" does not exist
  位置：8
; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: column "id" does not exist
  位置：8
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:101) ~[spring-jdbc-5.3.24.jar:5.3.24]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70) ~[spring-jdbc-5.3.24.jar:5.3.24]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79) ~[spring-jdbc-5.3.24.jar:5.3.24]

#### 友情提示（为了提高issue处理效率）：

1. 在online表单开发 --》功能测试，会弹出报错信息，报错类是org.jeecg.modules.online.cgform.mapper.OnlCgformButtonMapper

2.该类在hibernate-re包中。该包中使用的是mysql语法的查询，在postgresql中使用该语句查询字段要加"号。

**Comment by yjtcxd** [comment]
经过再次验证，postgresql在select时，如果表字段(姓名)是大写，必须要select "NAME" FROM ....

**Comment by zhangdaiscott** [comment]
不清楚，应该是你的数据库设置问题
