### ISSUE TITLE
缺少QRTZ_LOCKS表

### ISSUE THREAD

**Issue by superwg1984** [jeecgboot/jeecg-boot#5127]
##### 截图&代码：

提示缺少QRTZ_LOCKS表

#### 友情提示（为了提高issue处理效率）：
2023-07-06 17:52:22.068 [QuartzScheduler_MyScheduler-DESKTOP-HOME1688635908372_ClusterManager] ERROR druid.sql.Statement:148 - {conn-10003, pstmt-20398} execute error. SELECT * FROM QRTZ_LOCKS WHERE SCHED_NAME = 'MyScheduler' AND LOCK_NAME = ? FOR UPDATE
java.sql.SQLSyntaxErrorException: Table 'school.QRTZ_LOCKS' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)

**Comment by superwg1984** [comment]
问题找到了 mariadb 默认是 大小写敏感
