### ISSUE TITLE
online表单中的id会重复？又办法能让id不重复吗？

### ISSUE THREAD

**Issue by ciahua** [jeecgboot/jeecg-boot#5171]
##### 版本号：
v3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在online表单中生成的表，id字段沿用系统的算法，但是发现系统运行过程中id会出现重复，从而报错。请问你们的id算法是会重复的吗？有什么办法不重复吗？

##### 截图&代码：
----------------------------------代码信息-----------------------------------
sql = "insert into hmistatus (id, hid, hmiid, deviceid, devicedesc, ip, currstatus, starttime, endtime, duration, " +
                                                        "userid, username, shift, orderid, partnum_ja, operation, onoff, strokes)" +
                                                        "values (" + t4 + "," + 0 + ",'" + hmiid4 + "','" + did4 + "','" + desc4 + "','" + ip + "','" + keyStatus + "','" + ft4 + "','" + "" + "','" + "" + "','" + uid4 + "','" + name4 + "','" + shift + "','" + orderid + "','" + partnum_ja1 + "','" + operation + "','" + poweron + "','" + strokes + "');";

int n4a = DBHelper.executeNonQuery(sql);

----------------------------------报错信息-----------------------------------
java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '1689902686826' for key 'PRIMARY'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1334)
	at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2084)
	at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1245)
	at com.example.blserver.Util.DBHelper.executeNonQuery(DBHelper.java:45)
	at com.example.blserver.HmiService.HmiServer.dataAnalysis(HmiServer.java:744)
	at com.example.blserver.HmiService.HmiServer.dataHandler(HmiServer.java:185)
	at com.example.blserver.HmiService.HmiServer.dataHandler(HmiServer.java:163)
	at com.example.blserver.HmiService.HmiServer.startHmiService(HmiServer.java:140)
	at com.example.blserver.NettyService.BootNettyChannelInboundHandlerAdapter.channelRead(BootNettyChannelInboundHandlerAdapter.java:54)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
1689902686826 不是ID吧，我们的ID没这么短

**Comment by ciahua** [comment]
不是吗？我看通过online表单建立的表格，id都是这么短的啊。。。
![image](https://github.com/jeecgboot/jeecg-boot/assets/37827583/599f2da6-66ec-4b97-9f62-7ba045464422)

**Comment by ciahua** [comment]
这是表格的设置，id是用的默认设置啊。。。有啥不对吗？
![image](https://github.com/jeecgboot/jeecg-boot/assets/37827583/26dbae3a-3ab3-4e2e-aaa4-c302a501fc3a)

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/028a15f1-2069-40a8-a37f-c712cd448d16)

**Comment by ciahua** [comment]
是哦，我查一下。谢谢！
