### ISSUE TITLE
jeecg-cloud-nacos 打包镜像运行问题

### ISSUE THREAD

**Issue by m446883859** [jeecgboot/jeecg-boot#5379]
##### 版本号：3.5

Docker -v =Docker version 24.0.5, build ced0996
##### 问题描述：
对nacos组件打包运行后报错，
全新的代码，未做任何修改和处理。
 异常百度无法获取到有效帮助。

启动后可以正常看到欢迎图
![image](https://github.com/jeecgboot/jeecg-boot/assets/3964644/234862cc-32a0-4955-b5d8-96387487685f)

以下是部分异常日志：

2023-09-12 16:34:54 2023-09-12 16:34:54.012 ERROR 1 --- [           main] c.a.n.c.l.StartingApplicationListener    : Startup errors : 
2023-09-12 16:34:54 
2023-09-12 16:34:54 org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'namingHealthController': Unsatisfied dependency expressed through field 'healthOperatorV2'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'healthOperatorV2Impl' defined in URL [jar:file:/jeecg-cloud-nacos/jeecg-cloud-nacos-3.5.3.jar!/BOOT-INF/lib/nacos-naming-2.2.3.jar!/com/alibaba/nacos/naming/core/HealthOperatorV2Impl.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'clientOperationServiceProxy' defined in URL [jar:file:/jeecg-cloud-nacos/jeecg-cloud-nacos-3.5.3.jar!/BOOT-INF/lib/nacos-naming-2.2.3.jar!/com/alibaba/nacos/naming/core/v2/service/ClientOperationServiceProxy.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'persistentClientOperationServiceImpl' defined in URL [jar:file:/jeecg-cloud-nacos/jeecg-cloud-nacos-3.5.3.jar!/BOOT-INF/lib/nacos-naming-2.2.3.jar!/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperationServiceImpl]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni6703940578446525443.so: /tmp/librocksdbjni6703940578446525443.so: undefined symbol: _ZdlPvmSt11align_val_t
.....................................
最后的CaseBY
Caused by: java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni6703940578446525443.so: /tmp/librocksdbjni6703940578446525443.so: undefined symbol: _ZdlPvmSt11align_val_t
2023-09-12 16:34:54     at java.lang.ClassLoader$NativeLibrary.load(Native Method)
2023-09-12 16:34:54     at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
2023-09-12 16:34:54     at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
2023-09-12 16:34:54     at java.lang.Runtime.load0(Runtime.java:809)
2023-09-12 16:34:54     at java.lang.System.load(System.java:1086)
2023-09-12 16:34:54     at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:102)
2023-09-12 16:34:54     at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:82)
2023-09-12 16:34:54     at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:70)
2023-09-12 16:34:54     at org.rocksdb.RocksDB.<clinit>(RocksDB.java:39)
2023-09-12 16:34:54     at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.<clinit>(RocksDBLogStorage.java:77)
2023-09-12 16:34:54     at com.alipay.sofa.jraft.core.DefaultJRaftServiceFactory.createLogStorage(DefaultJRaftServiceFactory.java:50)
2023-09-12 16:34:54     at com.alipay.sofa.jraft.core.NodeImpl.initLogStorage(NodeImpl.java:580)
2023-09-12 16:34:54     at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:1005)
2023-09-12 16:34:54     at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:141)
2023-09-12 16:34:54     at com.alipay.sofa.jraft.RaftServiceFactory.createAndInitRaftNode(RaftServiceFactory.java:47)
2023-09-12 16:34:54     at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:129)
2023-09-12 16:34:54     at com.alibaba.nacos.core.distributed.raft.JRaftServer.createMultiRaftGroup(JRaftServer.java:260)
2023-09-12 16:34:54     at com.alibaba.nacos.core.distributed.raft.JRaftProtocol.addRequestProcessors(JRaftProtocol.java:163)
2023-09-12 16:34:54     at com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperationServiceImpl.<init>(PersistentClientOperationServiceImpl.java:96)
2023-09-12 16:34:54     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2023-09-12 16:34:54     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2023-09-12 16:34:54     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2023-09-12 16:34:54     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
2023-09-12 16:34:54     at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)

##### 截图&代码：
百度到的部分信息

![image](https://github.com/jeecgboot/jeecg-boot/assets/3964644/ad96f621-9552-4469-8a54-0c60ad7b913c)

**Comment by zhangdaiscott** [comment]
你是什么系统？

**Comment by m446883859** [comment]
生产环境Centos 8.2，  本地测试环境用的Docker Desktop 最新版，  问题是一样的

**Comment by zhangdaiscott** [comment]
等我们测测

**Comment by 280377485** [comment]
相同现象补充：
最新拉的官方代码，jdk1.8，本地微服务正常运行，在win10上严格按照操作手册用Docker Desk 4.20.1 (110738). 运行微服务会出现上述一样报错
