### ISSUE TITLE
钉钉第三方登录集成配置好了，但是登录页点击企业微信和钉钉都不能弹出二维码

### ISSUE THREAD

**Issue by wlbxh** [jeecgboot/jeecg-boot#5618]
##### 问题描述：
操作步骤：
01钉钉开放平台应用已经配置分享回调域名，如图
![01钉钉开放平台应用已经配置分享回调域名](https://github.com/jeecgboot/jeecg-boot/assets/152263539/5ab259f7-207e-475a-8359-c7746d0fa6ce)
02企业微信应用中已经配置授权回调域，如图
![02企业微信应用中已经配置授权回调域](https://github.com/jeecgboot/jeecg-boot/assets/152263539/a8c19264-52b3-4278-a1a5-07947430b89f)
03前端 env development配置了后台接口全路径地址，如图
![03前端 env development配置了后台接口全路径地址](https://github.com/jeecgboot/jeecg-boot/assets/152263539/3226ff99-40f1-40a3-9684-cb25ea222a3c)
04后台application-dev yml配置了企业微信和钉钉的参数，如图
![04后台application-dev yml配置了企业微信和钉钉的参数](https://github.com/jeecgboot/jeecg-boot/assets/152263539/5490fd6e-77b1-4b91-8d76-5cac71819538)

以上步骤都操作了，但是还是不能登录集成，请大佬帮忙排查一下。

##### 截图&代码：
![01钉钉开放平台应用已经配置分享回调域名](https://github.com/jeecgboot/jeecg-boot/assets/152263539/5ab259f7-207e-475a-8359-c7746d0fa6ce)
![02企业微信应用中已经配置授权回调域](https://github.com/jeecgboot/jeecg-boot/assets/152263539/a8c19264-52b3-4278-a1a5-07947430b89f)
![03前端 env development配置了后台接口全路径地址](https://github.com/jeecgboot/jeecg-boot/assets/152263539/3226ff99-40f1-40a3-9684-cb25ea222a3c)
![04后台application-dev yml配置了企业微信和钉钉的参数](https://github.com/jeecgboot/jeecg-boot/assets/152263539/5490fd6e-77b1-4b91-8d76-5cac71819538)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
在你的钉钉或者企业微信的回调地址上加上你的项目名称 你试一下

**Comment by 1298191366** [comment]
什么登录页面 看下截图我看看，前后台有没有报错，你有没有改前台逻辑，这是你的截图吗，看不了
![image](https://github.com/jeecgboot/jeecg-boot/assets/30997828/a7a191e8-c5f3-42df-b77e-d7039fdb5c4e)

**Comment by wlbxh** [comment]
目前部署的地址是http://cs.upacn.com:63100/


没有修改过前台逻辑，我就是原代码下载后根据环境部署配置，其他都没有改。

右键新页面，查看源代码，查看新页面的路径好像不对。







^Caiツ^^
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月4日(星期一) 晚上7:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 钉钉第三方登录集成配置好了，但是登录页点击企业微信和钉钉都不能弹出二维码 (Issue #5618)





 
什么登录页面 看下截图我看看，前后台有没有报错，你有没有改前台逻辑，这是你的截图吗，看不了
 image.png (view on web)

**Comment by 1298191366** [comment]
你是不是没有请求到后台，第三方登录的时候，他正常的话应该这个地址
![image](https://github.com/jeecgboot/jeecg-boot/assets/30997828/66d64fcb-a2d3-4c95-83b9-b8fee8e69b44)
后台应该有日志，你的回调接口是后台访问地址吗？
![image](https://github.com/jeecgboot/jeecg-boot/assets/30997828/a2671725-ecec-479a-846c-dc1e08a79f55)

**Comment by wlbxh** [comment]
后台请求地址在哪里配置呢？具体应该配置哪个地址？我目前是按文档配置步骤操作的，麻烦指点下，我的项目测试地址是http://cs.upacn.com:63100/




^Caiツ^^
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月5日(星期二) 上午10:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 钉钉第三方登录集成配置好了，但是登录页点击企业微信和钉钉都不能弹出二维码 (Issue #5618)





 
你是不是没有请求到后台，第三方登录的时候，他正常的话应该这个地址
 image.png (view on web)
 后台应该有日志，你的回调接口是后台访问地址吗？
 image.png (view on web)

**Comment by 1298191366** [comment]
就是你后台的访问地址，或者说你nginx映射的后台地址：你比如说我本地就是http://192.168.1.8080/jeecg-boot

**Comment by 1298191366** [comment]
就是这里配置的是你的后台访问地址
![image](https://github.com/jeecgboot/jeecg-boot/assets/30997828/b001ed77-9a9c-4611-b70b-ebaed7740151)

**Comment by wlbxh** [comment]
谢谢您，在您的耐心指导下二维码终于出来了，但是现在又有新的问题，就是扫码后出现如下错误，这个要怎么处理呢？


{"success":false,"message":"数据库中已存在该记录","code":500,"result":null,"timestamp":1701744360264}再次感谢您的指点！




^Caiツ^^
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月5日(星期二) 上午10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 钉钉第三方登录集成配置好了，但是登录页点击企业微信和钉钉都不能弹出二维码 (Issue #5618)





 
就是这里配置的是你的后台访问地址
 image.png (view on web)

**Comment by 1298191366** [comment]
可能是你数据库中存在老数据`sys_third_account`，或者说你改过应用，导致uuid冲突了，你目前需要删一下，目前是bug，已修复

**Comment by wlbxh** [comment]
谢谢您，已经处理，可以正常扫码，但是目前绑定手机号需要短信接口在哪里配置呢？




^Caiツ^^
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月5日(星期二) 上午10:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 钉钉第三方登录集成配置好了，但是登录页点击企业微信和钉钉都不能弹出二维码 (Issue #5618)





 
可能是你数据库中存在老数据sys_third_account，或者说你改过应用，导致uuid冲突了，你目前需要删一下，目前是bug，已修复

**Comment by 1298191366** [comment]
后台yml文件，需要配置oss，如果不需要验证码，你可以前台页面和后台接口注释掉(需要自行找一下)
![image](https://github.com/jeecgboot/jeecg-boot/assets/30997828/f95940dd-98f2-469f-ad0d-41523196f0ba)

**Comment by wlbxh** [comment]
账户设置页面，第三方APP配置，点击微信绑定出一App ID参数错误，这个个人微信可以配置吗？









^Caiツ^^
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月5日(星期二) 中午11:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 钉钉第三方登录集成配置好了，但是登录页点击企业微信和钉钉都不能弹出二维码 (Issue #5618)





 
后台yml文件，需要配置oss，如果不需要验证码，你可以前台页面和后台接口注释掉(需要自行找一下)
 image.png (view on web)

**Comment by wlbxh** [comment]
开发环境的根目录是哪个文件夹呢？


企业微信要添加可信IP才可以使用吗？
如下图这个文件WW_verify_WxTAfHdev685NrJn.txt放哪个目录下呢？
试了好几个目录都不行。







^Caiツ^^
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月5日(星期二) 中午11:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 钉钉第三方登录集成配置好了，但是登录页点击企业微信和钉钉都不能弹出二维码 (Issue #5618)





 
后台yml文件，需要配置oss，如果不需要验证码，你可以前台页面和后台接口注释掉(需要自行找一下)
 image.png (view on web)

**Comment by 1298191366** [comment]
企业微信扫码登录不需要域名检验
![image](https://github.com/jeecgboot/jeecg-boot/assets/30997828/8bde6106-7560-48bd-b0ce-9e8e6e9c6f7e)

**Comment by wlbxh** [comment]
但是我按文档配置后，出现以下错误，这个是为什么呢？
2023-12-06 14:22:49 http-nio-8080-exec-7 me.zhyd.oauth.log.Log(error:45) [ERROR] - Failed to login with oauth authorization.
me.zhyd.oauth.exception.AuthException: not allow to access from your ip, hint: [1701843769056942071418606], from ip: 115.236.95.10, more info at https://open.work.weixin.qq.com/devtool/query?e=60020 [WECHAT_ENTERPRISE]
	at me.zhyd.oauth.request.AuthWeChatEnterpriseRequest.checkResponse(AuthWeChatEnterpriseRequest.java:89)
	at me.zhyd.oauth.request.AuthWeChatEnterpriseRequest.getUserInfo(AuthWeChatEnterpriseRequest.java:55)
	at me.zhyd.oauth.request.AuthDefaultRequest.login(AuthDefaultRequest.java:81)
	at org.jeecg.modules.system.controller.ThirdLoginController.loginThird(ThirdLoginController.java:85)
	at org.jeecg.modules.system.controller.ThirdLoginController$$FastClassBySpringCGLIB$$630a7982.invoke(<generated&gt;)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at org.jeecg.common.aspect.DictAspect.doAround(DictAspect.java:62)
	at sun.reflect.GeneratedMethodAccessor157.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.jeecg.modules.system.controller.ThirdLoginController$$EnhancerBySpringCGLIB$$59bbc795.loginThird(<generated&gt;)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:502)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:596)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:114)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:458)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:373)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:370)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2023-12-06 14:22:49.782 [http-nio-8080-exec-7] INFO&nbsp; o.j.modules.system.controller.ThirdLoginController:86 - {"code":5000,"msg":"not allow to access from your ip, hint: [1701843769056942071418606], from ip: 115.236.95.10, more info at https://open.work.weixin.qq.com/devtool/query?e=60020 [WECHAT_ENTERPRISE]"}







^Caiツ^^
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月6日(星期三) 下午2:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 钉钉第三方登录集成配置好了，但是登录页点击企业微信和钉钉都不能弹出二维码 (Issue #5618)





 
企业微信扫码登录不需要域名检验
 image.png (view on web)

**Comment by 1298191366** [comment]
可以设置企业可信ip，但是好像新应用需要配置安全域名才可以设置
![image](https://github.com/jeecgboot/jeecg-boot/assets/30997828/dc11e7f6-65d3-47fd-ad93-ac64de598aa1)

**Comment by wlbxh** [comment]
配置安全域名，域名归属认证，需要下载下图文件放在开发环境的根目录，但是在开发环境根目录是哪个文件夹呢？


只域名归属认证好了，企业微信才可以添加可信IP。
如下图这个文件WW_verify_WxTAfHdev685NrJn.txt放哪个目录下呢？
试了好几个目录都不行。






^Caiツ^^
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月6日(星期三) 下午2:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 钉钉第三方登录集成配置好了，但是登录页点击企业微信和钉钉都不能弹出二维码 (Issue #5618)





 
可以设置企业可信ip，但是好像新应用需要配置安全域名才可以设置
 image.png (view on web)

**Comment by 1298191366** [comment]
看我上面的截图，应该是更新了

**Comment by wlbxh** [comment]
应该是企业微信开发平台更新了，那就没有办法测试了是吗？




^Caiツ^^
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月6日(星期三) 下午2:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 钉钉第三方登录集成配置好了，但是登录页点击企业微信和钉钉都不能弹出二维码 (Issue #5618)





 
看我上面的截图，应该是更新了

**Comment by 1298191366** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/30997828/a5499077-e4cf-4718-b000-c7b4665db849)

**Comment by wlbxh** [comment]
不好意思，这个完整的目录是哪个路径呢？在前端还是端呢？




^Caiツ^^
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月6日(星期三) 下午2:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 钉钉第三方登录集成配置好了，但是登录页点击企业微信和钉钉都不能弹出二维码 (Issue #5618)





 
image.png (view on web)

**Comment by 1298191366** [comment]
后端，比如我本地就是`jeecg-system-start/src/main/resources/static`，
![image](https://github.com/jeecgboot/jeecg-boot/assets/30997828/7e4fa83d-8fee-46cb-bd8f-a4200c96bf55)

**Comment by wlbxh** [comment]
奇怪了，我的目录下没有static这个文件夹，也没有看到META-INF文件夹，需要我手工创建static这个文件夹再放进来吗？









^Caiツ^^
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月6日(星期三) 下午3:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 钉钉第三方登录集成配置好了，但是登录页点击企业微信和钉钉都不能弹出二维码 (Issue #5618)





 
后端，比如我本地就是jeecg-system-start/src/main/resources/static，
 image.png (view on web)

**Comment by 1298191366** [comment]
对，我的static就是手工建的，静态资源是根据你yml中设置的
![image](https://github.com/jeecgboot/jeecg-boot/assets/30997828/7ca7ad63-9cf9-4f45-83fb-105cbcef0cfa)

**Comment by wlbxh** [comment]
我已经放在目录下面了，但是仍然访问不了，是不是我的这个访问路径不对呢？http://cs.upacn.com:63101/WW_verify_WxTAfHdev685NrJn.txt










^Caiツ^^
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月6日(星期三) 下午3:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 钉钉第三方登录集成配置好了，但是登录页点击企业微信和钉钉都不能弹出二维码 (Issue #5618)





 
对，我的static就是手工建的，静态资源是根据你yml中设置的
 image.png (view on web)

**Comment by 1298191366** [comment]
是的，你这个路径访问成功之后应该是能够看见证书的数据，具体你那需要怎么配置我就不清楚了
![image](https://github.com/jeecgboot/jeecg-boot/assets/30997828/093cf83c-358a-4b32-9541-8f282646c97c)
