### ISSUE TITLE
这个错误是什么意思呢？

### ISSUE THREAD

**Issue by wlbxh** [jeecgboot/jeecg-boot#5682]
##### 版本号：
Jeecg  Boot Version: 3.6.0
Spring Boot Version: 2.7.10 (v2.7.10)

##### 问题描述：
[plugin:vite:vue] <script> cannot use the "src" attribute when <script setup> is also present because they must be processed together.
D:/jeecgboot-vue3-master/src/views/dashboard/Analysis/components/GrowCard.vue
    at Object.parse$2 [as parse] (D:\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vue+compiler-sfc@3.3.6\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:1921:9)
    at createDescriptor (D:\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vitejs+plugin-vue@4.4.0_vite@4.5.0_vue@3.3.6\node_modules\@vitejs\plugin-vue\dist\index.cjs:86:43)
    at transformMain (D:\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vitejs+plugin-vue@4.4.0_vite@4.5.0_vue@3.3.6\node_modules\@vitejs\plugin-vue\dist\index.cjs:2298:34)
    at TransformContext.transform (D:\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vitejs+plugin-vue@4.4.0_vite@4.5.0_vue@3.3.6\node_modules\@vitejs\plugin-vue\dist\index.cjs:2830:16)
    at Object.transform (file:///D:/jeecgboot-vue3-master/node_modules/.pnpm/registry.npmmirror.com+vite@4.5.0_@types+node@20.8.7_less@4.2.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44352:62)
    at async loadAndTransform (file:///D:/jeecgboot-vue3-master/node_modules/.pnpm/registry.npmmirror.com+vite@4.5.0_@types+node@20.8.7_less@4.2.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:55026:29
Click outside, press Esc key, or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.

##### 截图&代码：
请大佬指点，谢谢。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
前端依赖删除了，重新install看看用pnpm
