### ISSUE TITLE
gateway无法启动

### ISSUE THREAD

**Issue by cometzhao** [jeecgboot/jeecg-boot#5724]
##### 版本号：
spring3版本3.6.1 

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
gateway无法启动

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/26214293/f0779e39-6f0c-4b2c-8e4b-32acb3c77cc2)

**Comment by zhangdaiscott** [comment]
刚测试可以启动，你确认下你的是jdk17吗
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/91dc94de-3e3a-4eaa-9f38-5d7968cc8ec3)

**Comment by cometzhao** [comment]
确认下是jdk17,fastjson问题
 <fastjson.version>2.0.43</fastjson.version>报错，降级到
<fastjson.version>1.2.83</fastjson.version>可启动。
详细报错：
![Snipaste_2023-12-27_17-07-56](https://github.com/jeecgboot/jeecg-boot/assets/26214293/28ec5e01-67af-4ecf-8054-1285b73166f9)
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
2023-12-27 17:07:00.803 [main] WARN  com.alibaba.nacos.client.logging.NacosLogging:64 - Load Logback Configuration of Nacos fail, message: Could not initialize Logback Nacos logging from classpath:nacos-logback.xml

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.1.5)

2023-12-27 17:07:00.819 [background-preinit] INFO  org.hibernate.validator.internal.util.Version:21 - HV000001: Hibernate Validator 8.0.1.Final
2023-12-27 17:07:00.857 [main] WARN  com.alibaba.nacos.client.logging.NacosLogging:64 - Load Logback Configuration of Nacos fail, message: Could not initialize Logback Nacos logging from classpath:nacos-logback.xml
2023-12-27 17:07:00.861 [main] INFO  org.jeecg.JeecgGatewayApplication:51 - Starting JeecgGatewayApplication using Java 17.0.9 with PID 32824 (D:\wwwroot\jeecgboot3\jeecg-boot-springboot3\jeecg-server-cloud\jeecg-cloud-gateway\target\classes started by R00005563 in D:\wwwroot\jeecgboot3\jeecg-boot-springboot3)
2023-12-27 17:07:00.863 [main] INFO  org.jeecg.JeecgGatewayApplication:638 - No active profile set, falling back to 1 default profile: "default"
2023-12-27 17:07:00.903 [main] INFO  c.a.cloud.nacos.configdata.NacosConfigDataLoader:250 - [Nacos Config] Load config[dataId=jeecg-gateway-dev.yaml, group=DEFAULT_GROUP] success
2023-12-27 17:07:01.790 [main] INFO  o.s.d.r.config.RepositoryConfigurationDelegate:291 - Multiple Spring Data modules found, entering strict repository configuration mode
2023-12-27 17:07:01.793 [main] INFO  o.s.d.r.config.RepositoryConfigurationDelegate:138 - Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2023-12-27 17:07:01.817 [main] INFO  o.s.d.r.config.RepositoryConfigurationDelegate:208 - Finished Spring Data repository scanning in 13 ms. Found 0 Redis repository interfaces.
2023-12-27 17:07:02.040 [main] INFO  o.springframework.cloud.context.scope.GenericScope:282 - BeanFactory id=eaea100d-1dec-39fb-a19e-d13cac372409
2023-12-27 17:07:02.264 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:409 - Bean 'org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration' of type [org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-12-27 17:07:02.265 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:409 - Bean 'org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration$ReactorDeferringLoadBalancerFilterConfig' of type [org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration$ReactorDeferringLoadBalancerFilterConfig] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-12-27 17:07:02.267 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:409 - Bean 'reactorDeferringLoadBalancerExchangeFilterFunction' of type [org.springframework.cloud.client.loadbalancer.reactive.DeferringLoadBalancerExchangeFilterFunction] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-12-27 17:07:02.750 [main] INFO  org.jeecg.common.modules.redis.config.RedisConfig:55 -  --- redis config init --- 
2023-12-27 17:07:02.906 [main] WARN  o.s.b.w.r.c.AnnotationConfigReactiveWebServerApplicationContext:624 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'feignEncoder' defined in class path resource [org/jeecg/config/FeignConfig.class]: Failed to instantiate [feign.codec.Encoder]: Factory method 'feignEncoder' threw exception with message: com/alibaba/fastjson/support/springfox/SwaggerJsonSerializer
2023-12-27 17:07:02.930 [main] INFO  o.s.b.a.logging.ConditionEvaluationReportLogger:82 - 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-12-27 17:07:02.942 [main] ERROR org.springframework.boot.SpringApplication:824 - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'feignEncoder' defined in class path resource [org/jeecg/config/FeignConfig.class]: Failed to instantiate [feign.codec.Encoder]: Factory method 'feignEncoder' threw exception with message: com/alibaba/fastjson/support/springfox/SwaggerJsonSerializer
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:654)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:488)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:950)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:616)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:738)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:440)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at org.jeecg.JeecgGatewayApplication.main(JeecgGatewayApplication.java:33)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [feign.codec.Encoder]: Factory method 'feignEncoder' threw exception with message: com/alibaba/fastjson/support/springfox/SwaggerJsonSerializer
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650)
	... 19 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/alibaba/fastjson/support/springfox/SwaggerJsonSerializer
	at org.jeecg.config.FeignConfig.getFastJsonConverter(FeignConfig.java:210)
	at org.jeecg.config.FeignConfig.feignHttpMessageConverter(FeignConfig.java:198)
	at org.jeecg.config.FeignConfig.feignEncoder(FeignConfig.java:184)
	at org.jeecg.config.FeignConfig$$SpringCGLIB$$0.CGLIB$feignEncoder$2(<generated>)
	at org.jeecg.config.FeignConfig$$SpringCGLIB$$FastClass$$1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at org.jeecg.config.FeignConfig$$SpringCGLIB$$0.feignEncoder(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139)
	... 20 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.alibaba.fastjson.support.springfox.SwaggerJsonSerializer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 33 common frames omitted
2023-12-27 17:07:03.425 [Thread-6] WARN  com.alibaba.nacos.common.notify.NotifyCenter:136 - [NotifyCenter] Start destroying Publisher
2023-12-27 17:07:03.426 [Thread-1] WARN  c.alibaba.nacos.common.http.HttpClientBeanHolder:102 - [HttpClientBeanHolder] Start destroying common HttpClient
2023-12-27 17:07:03.427 [Thread-6] WARN  com.alibaba.nacos.common.notify.NotifyCenter:153 - [NotifyCenter] Destruction of the end

Process finished with exit code 1

**Comment by zhangdaiscott** [comment]
你什么时候下载的代码？

**Comment by cometzhao** [comment]
不好意思，可能是IDEA的问题，打包后运行正常。
