### ISSUE TITLE
启动JeecgGatewayApplication时报错【org.jeecg.loader.DynamicRouteLoader.refresh】

### ISSUE THREAD

**Issue by shadowsock5** [jeecgboot/jeecg-boot#5779]
##### 版本号：
3.6.2

##### 前端版本：vue3版？还是 vue2版？
无关

##### 问题描述：
启动JeecgGatewayApplication时报错。

##### 截图&代码：

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v2.7.10)

2024-01-06 19:59:48.447 [background-preinit] INFO  org.hibernate.validator.internal.util.Version:21 - HV000001: Hibernate Validator 6.2.5.Final
2024-01-06 19:59:48.452 [main] INFO  org.jeecg.JeecgGatewayApplication:55 - Starting JeecgGatewayApplication using Java 1.8.0_202 on xxxxxxxx with PID 32276 (D:\repos\jeecg-boot-3.6.2\jeecg-server-cloud\jeecg-cloud-gateway\target\classes started by z004f5td in D:\repos\jeecg-boot-3.6.2)
2024-01-06 19:59:48.456 [main] INFO  org.jeecg.JeecgGatewayApplication:631 - No active profile set, falling back to 1 default profile: "default"
2024-01-06 19:59:49.873 [main] INFO  o.s.d.r.config.RepositoryConfigurationDelegate:262 - Multiple Spring Data modules found, entering strict repository configuration mode
2024-01-06 19:59:49.876 [main] INFO  o.s.d.r.config.RepositoryConfigurationDelegate:132 - Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2024-01-06 19:59:49.901 [main] INFO  o.s.d.r.config.RepositoryConfigurationDelegate:201 - Finished Spring Data repository scanning in 11 ms. Found 0 Redis repository interfaces.
2024-01-06 19:59:50.179 [main] INFO  o.springframework.cloud.context.scope.GenericScope:283 - BeanFactory id=d997a266-2cf8-3d51-8734-959fae5c925a
2024-01-06 19:59:50.540 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:376 - Bean 'org.springframework.cloud.commons.config.CommonsConfigAutoConfiguration' of type [org.springframework.cloud.commons.config.CommonsConfigAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-01-06 19:59:50.543 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:376 - Bean 'org.springframework.cloud.client.loadbalancer.LoadBalancerDefaultMappingsProviderAutoConfiguration' of type [org.springframework.cloud.client.loadbalancer.LoadBalancerDefaultMappingsProviderAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-01-06 19:59:50.544 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:376 - Bean 'loadBalancerClientsDefaultsMappingsProvider' of type [org.springframework.cloud.client.loadbalancer.LoadBalancerDefaultMappingsProviderAutoConfiguration$$Lambda$421/1644128841] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-01-06 19:59:50.546 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:376 - Bean 'defaultsBindHandlerAdvisor' of type [org.springframework.cloud.commons.config.DefaultsBindHandlerAdvisor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-01-06 19:59:50.636 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:376 - Bean 'org.hibernate.validator.internal.constraintvalidators.bv.notempty.NotEmptyValidatorForCharSequence' of type [org.hibernate.validator.internal.constraintvalidators.bv.notempty.NotEmptyValidatorForCharSequence] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-01-06 19:59:50.641 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:376 - Bean 'org.hibernate.validator.internal.constraintvalidators.bv.NotNullValidator' of type [org.hibernate.validator.internal.constraintvalidators.bv.NotNullValidator] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-01-06 19:59:50.701 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:376 - Bean 'spring.cloud.sentinel-com.alibaba.cloud.sentinel.SentinelProperties' of type [com.alibaba.cloud.sentinel.SentinelProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-01-06 19:59:50.708 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:376 - Bean 'com.alibaba.cloud.sentinel.custom.SentinelAutoConfiguration' of type [com.alibaba.cloud.sentinel.custom.SentinelAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-01-06 19:59:50.719 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:376 - Bean 'org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration' of type [org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-01-06 19:59:50.722 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:376 - Bean 'org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration$ReactorDeferringLoadBalancerFilterConfig' of type [org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration$ReactorDeferringLoadBalancerFilterConfig] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-01-06 19:59:50.724 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:376 - Bean 'reactorDeferringLoadBalancerExchangeFilterFunction' of type [org.springframework.cloud.client.loadbalancer.reactive.DeferringLoadBalancerExchangeFilterFunction] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-01-06 19:59:52.509 [main] INFO  o.s.c.gateway.route.RouteDefinitionRouteLocator:88 - Loaded RoutePredicateFactory [After]
2024-01-06 19:59:52.510 [main] INFO  o.s.c.gateway.route.RouteDefinitionRouteLocator:88 - Loaded RoutePredicateFactory [Before]
2024-01-06 19:59:52.510 [main] INFO  o.s.c.gateway.route.RouteDefinitionRouteLocator:88 - Loaded RoutePredicateFactory [Between]
2024-01-06 19:59:52.510 [main] INFO  o.s.c.gateway.route.RouteDefinitionRouteLocator:88 - Loaded RoutePredicateFactory [Cookie]
2024-01-06 19:59:52.510 [main] INFO  o.s.c.gateway.route.RouteDefinitionRouteLocator:88 - Loaded RoutePredicateFactory [Header]
2024-01-06 19:59:52.511 [main] INFO  o.s.c.gateway.route.RouteDefinitionRouteLocator:88 - Loaded RoutePredicateFactory [Host]
2024-01-06 19:59:52.511 [main] INFO  o.s.c.gateway.route.RouteDefinitionRouteLocator:88 - Loaded RoutePredicateFactory [Method]
2024-01-06 19:59:52.511 [main] INFO  o.s.c.gateway.route.RouteDefinitionRouteLocator:88 - Loaded RoutePredicateFactory [Path]
2024-01-06 19:59:52.511 [main] INFO  o.s.c.gateway.route.RouteDefinitionRouteLocator:88 - Loaded RoutePredicateFactory [Query]
2024-01-06 19:59:52.511 [main] INFO  o.s.c.gateway.route.RouteDefinitionRouteLocator:88 - Loaded RoutePredicateFactory [ReadBody]
2024-01-06 19:59:52.511 [main] INFO  o.s.c.gateway.route.RouteDefinitionRouteLocator:88 - Loaded RoutePredicateFactory [RemoteAddr]
2024-01-06 19:59:52.512 [main] INFO  o.s.c.gateway.route.RouteDefinitionRouteLocator:88 - Loaded RoutePredicateFactory [XForwardedRemoteAddr]
2024-01-06 19:59:52.512 [main] INFO  o.s.c.gateway.route.RouteDefinitionRouteLocator:88 - Loaded RoutePredicateFactory [Weight]
2024-01-06 19:59:52.512 [main] INFO  o.s.c.gateway.route.RouteDefinitionRouteLocator:88 - Loaded RoutePredicateFactory [CloudFoundryRouteService]
2024-01-06 19:59:52.539 [main] INFO  org.jeecg.common.modules.redis.config.RedisConfig:56 -  --- redis config init --- 
2024-01-06 20:00:43.110 [main] INFO  c.a.c.s.gateway.scg.SentinelSCGAutoConfiguration:144 - [Sentinel SpringCloudGateway] register SentinelGatewayFilter with order: -2147483648
2024-01-06 20:00:43.264 [main] INFO  o.s.b.actuate.endpoint.web.EndpointLinksResolver:58 - Exposing 1 endpoint(s) beneath base path '/actuator'
2024-01-06 20:00:44.095 [main] INFO  c.a.c.s.gateway.scg.SentinelSCGAutoConfiguration:134 - [Sentinel SpringCloudGateway] register SentinelGatewayBlockExceptionHandler
2024-01-06 20:00:44.599 [main] WARN  c.a.c.s.datasource.converter.SentinelConverter:79 - converter can not convert rules because source is empty
INFO: Sentinel log output type is: file
INFO: Sentinel log charset is: utf-8
INFO: Sentinel log base directory is: C:\Users\yyyyyyyy\logs\csp\
INFO: Sentinel log name use pid is: false
2024-01-06 20:00:44.630 [main] WARN  c.a.c.s.datasource.converter.SentinelConverter:79 - converter can not convert rules because source is empty
2024-01-06 20:00:44.640 [main] WARN  c.a.c.s.datasource.converter.SentinelConverter:79 - converter can not convert rules because source is empty
2024-01-06 20:00:44.660 [main] WARN  c.a.c.s.datasource.converter.SentinelConverter:79 - converter can not convert rules because source is empty
2024-01-06 20:00:44.840 [main] WARN  c.a.c.s.datasource.converter.SentinelConverter:79 - converter can not convert rules because source is empty
2024-01-06 20:00:44.854 [main] WARN  c.a.c.s.datasource.converter.SentinelConverter:79 - converter can not convert rules because source is empty
2024-01-06 20:00:44.869 [main] WARN  c.a.c.s.datasource.converter.SentinelConverter:79 - converter can not convert rules because source is empty
2024-01-06 20:00:45.383 [main] INFO  o.s.boot.web.embedded.netty.NettyWebServer:111 - Netty started on port 9999
2024-01-06 20:00:46.165 [main] INFO  c.a.cloud.nacos.registry.NacosServiceRegistry:75 - nacos registry, DEFAULT_GROUP jeecg-gateway 192.168.17.1:9999 register finished
2024-01-06 20:00:47.024 [main] INFO  org.jeecg.JeecgGatewayApplication:61 - Started JeecgGatewayApplication in 63.012 seconds (JVM running for 64.068)
2024-01-06 20:00:47.032 [main] INFO  org.jeecg.loader.DynamicRouteLoader:98 - 初始化路由模式，dataType：null
2024-01-06 20:00:47.046 [main] INFO  o.s.b.a.l.ConditionEvaluationReportLoggingListener:136 - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-01-06 20:00:47.094 [main] ERROR org.springframework.boot.SpringApplication:821 - Application run failed
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
	at org.jeecg.JeecgGatewayApplication.main(JeecgGatewayApplication.java:33)
Caused by: java.lang.NullPointerException: null
	at java.lang.String.endsWith(String.java:1449)
	at org.jeecg.loader.DynamicRouteLoader.refresh(DynamicRouteLoader.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
	at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.invoke(GenericScope.java:485)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.jeecg.loader.DynamicRouteLoader$$EnhancerBySpringCGLIB$$28507710.refresh(<generated>)
	at org.jeecg.JeecgGatewayApplication.run(JeecgGatewayApplication.java:44)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:768)
	... 5 common frames omitted
2024-01-06 20:00:47.115 [main] INFO  c.a.cloud.nacos.registry.NacosServiceRegistry:94 - De-registering from Nacos Server now...
2024-01-06 20:00:47.120 [main] INFO  c.a.cloud.nacos.registry.NacosServiceRegistry:114 - De-registration finished.
```

**Comment by shadowsock5** [comment]
不知道为什么获取不到。
![image](https://github.com/jeecgboot/jeecg-boot/assets/30398606/cb90771b-f539-4e12-910a-42adf33d4984)

**Comment by zhangdaiscott** [comment]
链接nacos了吗

**Comment by shadowsock5** [comment]
因为在`D:\repos\jeecg-boot-3.6.2\jeecg-server-cloud\jeecg-cloud-gateway\src\main\resources\application.yml`中有这些@符号，
```
  cloud:
    nacos:
      config:
        server-addr: @config.server-addr@
        group: @config.group@
        namespace: @config.namespace@
        username: @config.username@
        password: @config.password@
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        group: @config.group@
        namespace: @config.namespace@
        username: @config.username@
        password: @config.password@
```
然后启动的时候报错：
```
20:29:42.877 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'reader', line 30, column 22:
            server-addr: @config.server-addr@
```
我就把它换成了
```
  cloud:
    nacos:
      config:
        server-addr: jeecg-boot-nacos:8848
        username: nacos
        password: nacos
      discovery:
        server-addr: jeecg-boot-nacos:8848
        username: nacos
        password: nacos
```
不知道跟这个有没有关系。
然后nacos上配置是空的，不知道是不是正常的：
![image](https://github.com/jeecgboot/jeecg-boot/assets/30398606/9aefe345-0288-4cb6-97b0-a380c91c29c2)

感谢！

**Comment by zhangdaiscott** [comment]
刷新maven

**Comment by shadowsock5** [comment]
解决了，谢谢。nacos弄好了就都好了。
