### ISSUE TITLE
使用springboot+jdk17启动后端项目报错javax/servlet/http/HttpServletRequest

### ISSUE THREAD

**Issue by zhangxiaoning0** [jeecgboot/jeecg-boot#6051]
##### 版本号：
3.6.3

##### 问题描述：
使用springboot3+jdk17启动后端项目报错 Caused by: java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest

##### 截图&代码：
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-03-28 10:38:30.788 [main] ERROR org.springframework.boot.SpringApplication:824 - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shiroFilterFactoryBean' defined in class path resource [org/jeecg/config/shiro/ShiroConfig.class]: Failed to instantiate [org.apache.shiro.spring.web.ShiroFilterFactoryBean]: Factory method 'shiroFilter' threw exception with message: javax/servlet/http/HttpServletRequest
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:654)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:642)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:273)
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:796)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:600)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:738)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:440)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at org.jeecg.JeecgSystemApplication.main(JeecgSystemApplication.java:34)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.shiro.spring.web.ShiroFilterFactoryBean]: Factory method 'shiroFilter' threw exception with message: javax/servlet/http/HttpServletRequest
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650)
	... 19 common frames omitted
Caused by: java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
	at org.jeecg.config.shiro.ShiroConfig.collectIgnoreAuthUrl(ShiroConfig.java:360)
	at org.jeecg.config.shiro.ShiroConfig.shiroFilter(ShiroConfig.java:178)
	at org.jeecg.config.shiro.ShiroConfig$$SpringCGLIB$$0.CGLIB$shiroFilter$4(<generated>)
	at org.jeecg.config.shiro.ShiroConfig$$SpringCGLIB$$FastClass$$1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at org.jeecg.config.shiro.ShiroConfig$$SpringCGLIB$$0.shiroFilter(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139)
	... 20 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpServletRequest
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 35 common frames omitted
Disconnected from the target VM, address: '127.0.0.1:58239', transport: 'socket'

Process finished with exit code 1
![图片](https://github.com/jeecgboot/jeecg-boot/assets/31060119/ee78c1a5-f2c9-4597-89ff-986fb5067145)
![图片](https://github.com/jeecgboot/jeecg-boot/assets/31060119/226f5e55-ba51-48fd-8076-e98f318878ba)
![图片](https://github.com/jeecgboot/jeecg-boot/assets/31060119/58494256-d16f-4eb9-8694-64b156c3d73c)
![图片](https://github.com/jeecgboot/jeecg-boot/assets/31060119/52d62de5-b279-4ce8-bc54-9159748d3463)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by EightMonth** [comment]
请问你使用的是哪个分支，只有springboot3\springboot3_sas分支才支持JDK17，master分支并不支持
经本地测试，springboot3\springboot3_sas分支均未复现该问题

**Comment by zhangxiaoning0** [comment]
> 请问你使用的是哪个分支，只有springboot3\springboot3_sas分支才支持JDK17，master分支并不支持 经本地测试，springboot3\springboot3_sas分支均未复现该问题

我用的是springboot3这个分支
应该是我改了这几个依赖导致的
![图片](https://github.com/jeecgboot/jeecg-boot/assets/31060119/35703d87-6b9b-4608-be9f-f64850184a69)
![图片](https://github.com/jeecgboot/jeecg-boot/assets/31060119/4342959e-4d7e-41e1-b193-66c0e0b74708)
![图片](https://github.com/jeecgboot/jeecg-boot/assets/31060119/db56f520-a347-45bf-849b-49efae998fc5)

我看这几个依赖从https://maven.aliyun.com/repository/public下载不到就改成了org.jeecgframework.boot 的hibernate-re和org.jeecgframework.boot的jimureport-drag的2.0.1版本了 虽然能更新到依赖包  但是启动就报上面的错误，我把这些改动还原了可以启动了

**Comment by EightMonth** [comment]
在springboot3对应的版本都是适配过springboot3和JDK17的版本，不能随意更改

**Comment by zhangxiaoning0** [comment]
> 在springboot3对应的版本都是适配过springboot3和JDK17的版本，不能随意更改

那像是这种依赖包从 https://maven.aliyun.com/repository/public下载不到的其实也不影响后端的正常使用是吧  因为我确实在阿里云的这个仓库里面没有找到org.jeecgframework.boot3 的hibernate-re 或者 org.jeecgframework.boot3的jimureport-drag的2.0.2等上面我截图里面的依赖版本

**Comment by EightMonth** [comment]
https://help.jeecg.com/java/setup/maven.html
maven配置这个地址
